### PR TITLE
Upgrade rspec

### PR DESCRIPTION
**Pull request by h-lame**
Upgrade from RSpec 2 to RSpec 3.  Commits tell the story about each change, so it'll be more useful review that way.

### CODE REVIEW

**Comment by brenetic** [comment]
:+1: Great commit messages @h-lame

**Comment by davidbasalla** [comment]
Looks good to me, left some minor comments on making the commit messages adhere to the styleguide

**Comment by h-lame** [comment]
Reworded / merged some commits.  Thanks for the comments.

**Comment by benlovell** [comment]
:sparkles: :+1:

**Pull request merged**
