### PR TITLE
Use SimpleCov to monitor code coverage

### PR DESCRIPTION
**Pull request by benthorner**
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review

We should always monitor the amount of code that is exercised when
we run our tests.

### CODE REVIEW

**Comment by kevindew** [comment]
It looks like this produces two different coverage reports (RSpec and Cucumer) do we not want a single one that combines them both? I've no idea if that's possible, mind.

**Comment by benthorner** [comment]
It does produce two reports, but they're distinct and [automatically aggregated by SimpleCov](https://github.com/simplecov-ruby/simplecov#merging-results):

```
{
  "RSpec": {
    "coverage": {
      "/govuk/transition/app/controllers/concerns/track_mappings_progress.rb": {
        "lines": [
          1,

...

    "timestamp": 1600778396
  },
  "Cucumber Features": {
    "coverage": {
      "/govuk/transition/app/controllers/concerns/track_mappings_progress.rb": {
        "lines": [
          1,

...
```

**Comment by kevindew** [comment]
Oh cool, so are we going to generate something with the file produced?

Thanks for explaining.

**Review by kevindew — APPROVED** [review]

**Comment by benthorner** [comment]
> Oh cool, so are we going to generate something with the file produced?

I'm not sure I follow. The combined coverage is visible in the `coverage/index.html` file, although it doesn't indicate what (kind of) test is covering the code. We get the web page report by default - perhaps that was an unknown for you?

**Comment by kevindew** [comment]
> > Oh cool, so are we going to generate something with the file produced?
> 
> I'm not sure I follow. The combined coverage is visible in the `coverage/index.html` file, although it doesn't indicate what (kind of) test is covering the code. We get the web page report by default - perhaps that was an unknown for you?

Sorry I wasn't very clear. I know that currently a file is created, however Jenkins doesn't do anything with it (as far as I'm aware) so I wondered if we'd be using it as part of a step or process.

**Comment by benthorner** [comment]
Discussed in person and all is well: the aggregated coverage is visible in a single file; the use of SimpleCov is primarily for some minimal visibility on a local machine, although we could monitor it more comprehensively in future.

**Pull request merged**
